import type { Metadata } from "next";
import { Toaster } from 'react-hot-toast';
import "./globals.css";
import {Navbar} from "./navbar";
import {Footer} from "./footer";
import {Providers} from "./providers";
import { LanguageProvider } from '@/context/LanguageContext';
import { TranslationProvider } from '@/i18n';
import RTLWrapper from './components/RTLWrapper';
import { geistSans, geistMono } from './utils/fonts';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0a0a0a" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://backend-for-global-shop-production-a385.up.railway.app" />
        <link rel="dns-prefetch" href="https://backend-for-global-shop-production-a385.up.railway.app" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <LanguageProvider>
          <TranslationProvider>
            <Providers>
              <Toaster position="top-right" toastOptions={{
                duration: 3000,
                style: {
                  background: '#363636',
                  color: '#fff',
                },
                success: {
                  iconTheme: {
                    primary: '#10b981',
                    secondary: '#fff',
                  },
                },
                error: {
                  iconTheme: {
                    primary: '#ef4444',
                    secondary: '#fff',
                  },
                },
              }} />
              <Navbar />
              <RTLWrapper>
                {children}
              </RTLWrapper>
              <Footer />
            </Providers>
          </TranslationProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
