import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from 'react-hot-toast';
import "./globals.css";
import {Navbar} from "./navbar";
import {Footer} from "./footer";
import {Providers} from "./providers";
import { LanguageProvider } from '@/context/LanguageContext';
import { TranslationProvider } from '@/i18n';
import RTLWrapper from './components/RTLWrapper';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <LanguageProvider>
          <TranslationProvider>
            <Providers>
              <Toaster position="top-right" toastOptions={{
                duration: 3000,
                style: {
                  background: '#363636',
                  color: '#fff',
                },
                success: {
                  iconTheme: {
                    primary: '#10b981',
                    secondary: '#fff',
                  },
                },
                error: {
                  iconTheme: {
                    primary: '#ef4444',
                    secondary: '#fff',
                  },
                },
              }} />
              <Navbar />
              <RTLWrapper>
                {children}
              </RTLWrapper>
              <Footer />
            </Providers>
          </TranslationProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
